[versions]
koin = "4.1.2-Beta1"
kotlin = "2.3.0"
ktor = "3.4.2"
logback = "1.4.14"
prometheus = "1.6.13"
mongodb-bom = "5.6.4"
jb-crypt = "0.4"
resend = "4.13.0"
aws-s3 = "1.4.113"
jsoup = "1.22.1"
kotlinx-datetime = "0.6.1"
firebase-admin = "9.4.3"

[libraries]
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serialization-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-metrics-micrometer = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "prometheus" }
ktor-server-metrics = { module = "io.ktor:ktor-server-metrics", version.ref = "ktor" }
cohort-ktor = { module = "com.sksamuel.cohort:cohort-ktor", version = "2.7.2" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-server-request-validation = { module = "io.ktor:ktor-server-request-validation", version.ref = "ktor" }
ktor-server-csrf = { module = "io.ktor:ktor-server-csrf", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-mongodb-bom = { module = "org.mongodb:mongodb-driver-bom", version.ref = "mongodb-bom" }
kotlin-mongodb-driver-coroutine = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version.ref = "mongodb-bom" }
kotlin-mongodb-bson-kotlinx = { module = "org.mongodb:bson-kotlinx", version.ref = "mongodb-bom" }
jb-crypt = { module = "org.mindrot:jbcrypt", version.ref = "jb-crypt"}
kotlin-resend = { module = "com.resend:resend-java", version.ref = "resend"}
kotlin-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor"}
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
kotlin-aws-s3 = { module = "aws.sdk.kotlin:s3", version.ref  = "aws-s3"}
kotlin-jsoup  = { module = "org.jsoup:jsoup", version.ref = "jsoup"}
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
firebase-admin = { module = "com.google.firebase:firebase-admin", version.ref = "firebase-admin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
